### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by olivier-salmon** [svrnm/DemoMonkey#134] opened 2023-03-07 22:52 UTC
This is the error I'm seeing in the logs, however I can't tell for sure if it's related with my issue or not.

It's been a while now since I randomly have issues with Demo Monkey. When Duplicating templates, or editing existing ones, sometimes (and I would say more and more often) you can click on Save, but the configuration is not saved.

I'm on the latest chrome and lates MacOs version.

**Comment by svrnm** [comment] 2023-03-13 10:26
this error is unrelated, but see #131, we see this happening more often right now, this is related to the changes that were necessary to support Manifest Version 3.

**Comment by svrnm** [comment] 2024-12-12 15:53
duplicate of #131, will close this now, please reopen it if you think it's a different issue and/or if your issue persists

**Closed by svrnm** 2024-12-12 15:53 UTC
